spring:
  application:
    name: ddtube
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
ddtube:
  playlist:
    code_length: 5
    delete_hours: 6
    priority_step: 100_000_000_000_000
  user:
    code_length: 5
  video:
    code_length: 5
  sse:
    time_out: 1000L * 60 * 30 # 30분