spring:
  application:
    name: ddtube
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  pattern:
    console: "%yellow(%d{yyyy-MM-ddTHH:mm:ss.SSS}) [%20.20thread] %highlight(%-5level) %cyan(%-30.30C{0}) - %msg%n"
ddtube:
  playlist:
    code_length: 5
    delete_hours: 6
    priority_step: 100_000_000_000_000
  user:
    code_length: 5
  video:
    code_length: 5
  sse:
    time_out: 1_800_000 # 30분 1000L * 60 * 30