spring:
  application:
    name: ddtube
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
ddtube:
  playlist:
    code_length: 5
    delete_hours: 6
  user:
    code_length: 5
  video:
    code_length: 5